version: '3.9'

services:
  gateway:
    build:
      context: ./agritech-platform/gateway
    ports:
      - "8085:8085"
    depends_on:
      - auth-service
      - farm-service
      - telemetry-service
      - analytics-service
    environment:
      SPRING_PROFILES_ACTIVE: default

  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "8081:8081"

  farm-service:
    build:
      context: ./services/farm-service
    ports:
      - "8082:8082"

  telemetry-service:
    build:
      context: ./services/telemetry-service
    ports:
      - "8083:8083"

  analytics-service:
    build:
      context: ./services/analytics-service
    ports:
      - "8084:8084"
