server.port=8081

spring.application.name=auth-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Auth Service
info.app.description=Authentication and user management service
info.app.version=1.0.0
info.service.port=8081
