spring.application.name=precision-agri-platform
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

app.jwt.secret=change-this-to-a-long-random-secret-at-least-32-bytes-in-production
app.jwt.expiration-ms=86400000
app.irrigation.strategy=threshold
app.irrigation.ml-endpoint=http://localhost:8500/predict
app.scheduler.irrigation-sweep-ms=300000
app.scheduler.offline-sweep-ms=300000
app.scheduler.analytics-cron=0 10 0 * * *
app.nwdp.base-url=https://www.nwdp.nwic.gov.in/api/3/action/datastore_search
app.nwdp.resource-id=a2a13ede-4a16-4484-a66d-e7953cbd57bb
