server.port=8082

spring.application.name=farm-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Farm Service
info.app.description=Farm and field management service
info.app.version=1.0.0
info.service.port=8082
